<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\StockSharp (GitHub)\common_target_tests.props" />
  <ItemGroup>
    <ProjectReference Include="..\Aerodrome\Aerodrome.csproj" />
	<ProjectReference Include="..\Velodrome\Velodrome.csproj" />
    <ProjectReference Include="..\Aevo\Aevo.csproj" />
    <ProjectReference Include="..\AlorHistory\AlorHistory.csproj" />
	<ProjectReference Include="..\AltCoinTrader\AltCoinTrader.csproj" />
    <ProjectReference Include="..\ApexOmni\ApexOmni.csproj" />
	<ProjectReference Include="..\AscendEx\AscendEx.csproj" />
    <ProjectReference Include="..\Aster\Aster.csproj" />
    <ProjectReference Include="..\Avantis\Avantis.csproj" />
    <ProjectReference Include="..\Backpack\Backpack.csproj" />
    <ProjectReference Include="..\Balancer\Balancer.csproj" />
    <ProjectReference Include="..\Bcs\Bcs.csproj" />
    <ProjectReference Include="..\Bigul\Bigul.csproj" />
    <ProjectReference Include="..\Binance\Binance.csproj" />
    <ProjectReference Include="..\BingX\BingX.csproj" />
	<ProjectReference Include="..\BigOne\BigOne.csproj" />
	<ProjectReference Include="..\Bit2Me\Bit2Me.csproj" />
	<ProjectReference Include="..\BitoPro\BitoPro.csproj" />
    <ProjectReference Include="..\Bitbank\Bitbank.csproj" />
    <ProjectReference Include="..\Bitfinex\Bitfinex.csproj" />
    <ProjectReference Include="..\BitFlyer\BitFlyer.csproj" />
    <ProjectReference Include="..\Bitget\Bitget.csproj" />
    <ProjectReference Include="..\Bitkub\Bitkub.csproj" />
    <ProjectReference Include="..\Bitmart\Bitmart.csproj" />
    <ProjectReference Include="..\Bitmex\Bitmex.csproj" />
    <ProjectReference Include="..\Bitrue\Bitrue.csproj" />
    <ProjectReference Include="..\Bitso\Bitso.csproj" />
    <ProjectReference Include="..\BitStamp\BitStamp.csproj" />
    <ProjectReference Include="..\Bitunix\Bitunix.csproj" />
    <ProjectReference Include="..\Bitvavo\Bitvavo.csproj" />
    <ProjectReference Include="..\BloFin\BloFin.csproj" />
    <ProjectReference Include="..\Bluefin\Bluefin.csproj" />
    <ProjectReference Include="..\BTCMarkets\BTCMarkets.csproj" />
	<ProjectReference Include="..\BtcTurk\BtcTurk.csproj" />
	<ProjectReference Include="..\Buda\Buda.csproj" />
    <ProjectReference Include="..\BTSE\BTSE.csproj" />
    <ProjectReference Include="..\ByBit\ByBit.csproj" />
    <ProjectReference Include="..\BYDFi\BYDFi.csproj" />
	<ProjectReference Include="..\Chainflip\Chainflip.csproj" />
    <ProjectReference Include="..\Cetus\Cetus.csproj" />
    <ProjectReference Include="..\Cex\Cex.csproj" />
    <ProjectReference Include="..\ChoiceFinX\ChoiceFinX.csproj" />
    <ProjectReference Include="..\Coinbase\Coinbase.csproj" />
    <ProjectReference Include="..\Coincheck\Coincheck.csproj" />
    <ProjectReference Include="..\CoinDCX\CoinDCX.csproj" />
    <ProjectReference Include="..\CoinEx\CoinEx.csproj" />
    <ProjectReference Include="..\CoinJar\CoinJar.csproj" />
    <ProjectReference Include="..\CoinMarketCap\CoinMarketCap.csproj" />
    <ProjectReference Include="..\Coinone\Coinone.csproj" />
	<ProjectReference Include="..\CoinTR\CoinTR.csproj" />
	<ProjectReference Include="..\CoinSwitch\CoinSwitch.csproj" />
	<ProjectReference Include="..\CoinCatch\CoinCatch.csproj" />
	<ProjectReference Include="..\Coinmetro\Coinmetro.csproj" />
	<ProjectReference Include="..\LCX\LCX.csproj" />
	<ProjectReference Include="..\WazirX\WazirX.csproj" />
	<ProjectReference Include="..\DeltaExchangeIndia\DeltaExchangeIndia.csproj" />
	<ProjectReference Include="..\Dexalot\Dexalot.csproj" />
	<ProjectReference Include="..\StonFi\StonFi.csproj" />
	<ProjectReference Include="..\Xrpl\Xrpl.csproj" />
	<ProjectReference Include="..\Settrade\Settrade.csproj" />
	<ProjectReference Include="..\Shoonya\Shoonya.csproj" />
	<ProjectReference Include="..\SSI\SSI.csproj" />
	<ProjectReference Include="..\IIFL\IIFL.csproj" />
	<ProjectReference Include="..\MStock\MStock.csproj" />
	<ProjectReference Include="..\Samco\Samco.csproj" />
	<ProjectReference Include="..\JQuants\JQuants.csproj" />
	<ProjectReference Include="..\MarketDataApp\MarketDataApp.csproj" />
	<ProjectReference Include="..\SecEdgar\SecEdgar.csproj" />
	<ProjectReference Include="..\OpenFigi\OpenFigi.csproj" />
	<ProjectReference Include="..\SimFin\SimFin.csproj" />
	<ProjectReference Include="..\TraderMade\TraderMade.csproj" />
	<ProjectReference Include="..\Finage\Finage.csproj" />
	<ProjectReference Include="..\Coincall\Coincall.csproj" />
	<ProjectReference Include="..\CoinPaprika\CoinPaprika.csproj" />
	<ProjectReference Include="..\CoinGlass\CoinGlass.csproj" />
	<ProjectReference Include="..\Coinalyze\Coinalyze.csproj" />
	<ProjectReference Include="..\DexScreener\DexScreener.csproj" />
	<ProjectReference Include="..\Birdeye\Birdeye.csproj" />
	<ProjectReference Include="..\ZeroX\ZeroX.csproj" />
	<ProjectReference Include="..\KyberSwap\KyberSwap.csproj" />
	<ProjectReference Include="..\Velora\Velora.csproj" />
	<ProjectReference Include="..\DeepBook\DeepBook.csproj" />
	<ProjectReference Include="..\CoinSpot\CoinSpot.csproj" />
    <ProjectReference Include="..\CoinsPh\CoinsPh.csproj" />
	<ProjectReference Include="..\Coinstore\Coinstore.csproj" />
    <ProjectReference Include="..\Comdirect\Comdirect.csproj" />
    <ProjectReference Include="..\CowProtocol\CowProtocol.csproj" />
    <ProjectReference Include="..\CryptoCom\CryptoCom.csproj" />
    <ProjectReference Include="..\Curve\Curve.csproj" />
    <ProjectReference Include="..\Deepcoin\Deepcoin.csproj" />
    <ProjectReference Include="..\Definedge\Definedge.csproj" />
    <ProjectReference Include="..\Deribit\Deribit.csproj" />
    <ProjectReference Include="..\Deriv\Deriv.csproj" />
    <ProjectReference Include="..\Digifinex\Digifinex.csproj" />
    <ProjectReference Include="..\Directa\Directa.csproj" />
    <ProjectReference Include="..\Drift\Drift.csproj" />
	<ProjectReference Include="..\DukasCopyJForex\DukasCopyJForex.csproj" />
    <ProjectReference Include="..\DydxChain\DydxChain.csproj" />
    <ProjectReference Include="..\edgeX\EdgeX.csproj" />
    <ProjectReference Include="..\Exante\Exante.csproj" />
    <ProjectReference Include="..\Exmo\Exmo.csproj" />
    <ProjectReference Include="..\Extended\Extended.csproj" />
    <ProjectReference Include="..\FivePaisa\FivePaisa.csproj" />
	<ProjectReference Include="..\FinamTrade\FinamTrade.csproj" />
    <ProjectReference Include="..\Firstock\Firstock.csproj" />
    <ProjectReference Include="..\FluidDex\FluidDex.csproj" />
    <ProjectReference Include="..\Foxbit\Foxbit.csproj" />
    <ProjectReference Include="..\FXOpen\FXOpen.csproj" />
    <ProjectReference Include="..\GainsNetwork\GainsNetwork.csproj" />
    <ProjectReference Include="..\GateIO\GateIO.csproj" />
    <ProjectReference Include="..\Gemini\Gemini.csproj" />
    <ProjectReference Include="..\GmoCoin\GmoCoin.csproj" />
    <ProjectReference Include="..\GMTrade\GMTrade.csproj" />
    <ProjectReference Include="..\Gmx\Gmx.csproj" />
    <ProjectReference Include="..\Gopax\Gopax.csproj" />
    <ProjectReference Include="..\Grvt\Grvt.csproj" />
    <ProjectReference Include="..\HashKey\HashKey.csproj" />
    <ProjectReference Include="..\HdfcSecurities\HdfcSecurities.csproj" />
    <ProjectReference Include="..\HitBtc\HitBtc.csproj" />
    <ProjectReference Include="..\Huobi\Huobi.csproj" />
    <ProjectReference Include="..\Hyperliquid\Hyperliquid.csproj" />
    <ProjectReference Include="..\IndependentReserve\IndependentReserve.csproj" />
    <ProjectReference Include="..\Indodax\Indodax.csproj" />
    <ProjectReference Include="..\Injective\Injective.csproj" />
    <ProjectReference Include="..\Intrinio\Intrinio.csproj" />
    <ProjectReference Include="..\Jainam\Jainam.csproj" />
    <ProjectReference Include="..\Jupiter\Jupiter.csproj" />
    <ProjectReference Include="..\Kalshi\Kalshi.csproj" />
    <ProjectReference Include="..\Korbit\Korbit.csproj" />
    <ProjectReference Include="..\Kraken\Kraken.csproj" />
    <ProjectReference Include="..\Kucoin\Kucoin.csproj" />
    <ProjectReference Include="..\Latoken\Latoken.csproj" />
    <ProjectReference Include="..\LBank\LBank.csproj" />
    <ProjectReference Include="..\Lfj\Lfj.csproj" />
    <ProjectReference Include="..\Ligther\Ligther.csproj" />
    <ProjectReference Include="..\Luno\Luno.csproj" />
    <ProjectReference Include="..\ManifestTrade\ManifestTrade.csproj" />
	<ProjectReference Include="..\MaxExchange\MaxExchange.csproj" />
    <ProjectReference Include="..\Mastertrust\Mastertrust.csproj" />
    <ProjectReference Include="..\MercadoBitcoin\MercadoBitcoin.csproj" />
    <ProjectReference Include="..\MetaApi\MetaApi.csproj" />
    <ProjectReference Include="..\Meteora\Meteora.csproj" />
    <ProjectReference Include="..\Mexc\Mexc.csproj" />
    <ProjectReference Include="..\MoexISS\MoexISS.csproj" />
    <ProjectReference Include="..\Nado\Nado.csproj" />
    <ProjectReference Include="..\NDAX\NDAX.csproj" />
    <ProjectReference Include="..\Noren\Noren.csproj" />
	<ProjectReference Include="..\NovaDax\NovaDax.csproj" />
    <ProjectReference Include="..\Nubra\Nubra.csproj" />
    <ProjectReference Include="..\Nuvama\Nuvama.csproj" />
    <ProjectReference Include="..\Okex\Okex.csproj" />
    <ProjectReference Include="..\OkexHistory\OkexHistory.csproj" />
    <ProjectReference Include="..\Orca\Orca.csproj" />
    <ProjectReference Include="..\OrderlyNetwork\OrderlyNetwork.csproj" />
    <ProjectReference Include="..\OSL\OSL.csproj" />
    <ProjectReference Include="..\Osmosis\Osmosis.csproj" />
    <ProjectReference Include="..\Ostium\Ostium.csproj" />
    <ProjectReference Include="..\Ourbit\Ourbit.csproj" />
    <ProjectReference Include="..\Pacifica\Pacifica.csproj" />
    <ProjectReference Include="..\Paxos\Paxos.csproj" />
    <ProjectReference Include="..\PaytmMoney\PaytmMoney.csproj" />
	<ProjectReference Include="..\Pendle\Pendle.csproj" />
    <ProjectReference Include="..\Phemex\Phemex.csproj" />
    <ProjectReference Include="..\Pionex\Pionex.csproj" />
    <ProjectReference Include="..\Polymarket\Polymarket.csproj" />
    <ProjectReference Include="..\Public\Public.csproj" />
    <ProjectReference Include="..\PumpSwap\PumpSwap.csproj" />
    <ProjectReference Include="..\QFEX\QFEX.csproj" />
	<ProjectReference Include="..\Quidax\Quidax.csproj" />
    <ProjectReference Include="..\Raydium\Raydium.csproj" />
    <ProjectReference Include="..\Reya\Reya.csproj" />
    <ProjectReference Include="..\Rupeezy\Rupeezy.csproj" />
    <ProjectReference Include="..\StandX\StandX.csproj" />
    <ProjectReference Include="..\StocksTrader\StocksTrader.csproj" />
    <ProjectReference Include="..\SunIo\SunIo.csproj" />
    <ProjectReference Include="..\SynFutures\SynFutures.csproj" />
    <ProjectReference Include="..\Synthetix\Synthetix.csproj" />
    <ProjectReference Include="..\THORChain\THORChain.csproj" />
	<ProjectReference Include="..\Tokocrypto\Tokocrypto.csproj" />
    <ProjectReference Include="..\Toobit\Toobit.csproj" />
    <ProjectReference Include="..\Tradernet\Tradernet.csproj" />
    <ProjectReference Include="..\Tradejini\Tradejini.csproj" />
    <ProjectReference Include="..\Upbit\Upbit.csproj" />
    <ProjectReference Include="..\VALR\VALR.csproj" />
    <ProjectReference Include="..\VariationalOmni\VariationalOmni.csproj" />
    <ProjectReference Include="..\Ventura\Ventura.csproj" />
    <ProjectReference Include="..\Weex\Weex.csproj" />
    <ProjectReference Include="..\WhiteBit\WhiteBit.csproj" />
    <ProjectReference Include="..\WooX\WooX.csproj" />
    <ProjectReference Include="..\Xt\Xt.csproj" />
    <ProjectReference Include="..\Yobit\Yobit.csproj" />
    <ProjectReference Include="..\Zebu\Zebu.csproj" />
	<ProjectReference Include="..\ZondaCrypto\ZondaCrypto.csproj" />
    <ProjectReference Include="..\Zoomex\Zoomex.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="TonSdk.Core" Version="$(TonSdkCoreVer)" />
  </ItemGroup>
</Project>
